version: '3'

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn core.wsgi --bind 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=0
    ports:
      - 80:8000
    expose:
      - 80
