# Generated by Django 4.1.1 on 2022-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modelpettest'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpettest',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/petstes/'),
        ),
    ]
