# Generated by Django 4.1.1 on 2022-09-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modelpettest_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.CharField(default='Miami', max_length=66),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='Macho', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
