# Generated by Django 4.1.1 on 2022-09-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pet_sex_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2),
        ),
    ]
