# Generated by Django 4.1.1 on 2022-09-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pet_age_pet_city_pet_sex_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(default='Lima', max_length=66),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(default='Mediano', max_length=10),
        ),
    ]
