# Generated by Django 4.1.1 on 2022-09-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_pet_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelPetTest',
        ),
    ]
