# Generated by Django 4.1.1 on 2022-10-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type_pet',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', max_length=10),
        ),
    ]
