# Generated by Django 4.1.1 on 2022-10-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(default='Lima', max_length=66),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_pet',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], default='Perro', max_length=10),
        ),
    ]
