# Generated by Django 4.1.1 on 2022-10-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_pet_city_alter_pet_type_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2),
        ),
    ]
