# Generated by Django 4.1.1 on 2022-10-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('1', 'Pequeño'), ('2', 'Mediano'), ('3', 'Grande')], max_length=1),
        ),
    ]
