# Generated by Django 4.1.1 on 2022-10-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
    ]
