# Generated by Django 4.1.1 on 2022-09-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_recuperation', '0002_rename_key_secret_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='is_active',
        ),
    ]
